unit TestFuncionarioUn;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, System.Classes, LibUtils, FuncionarioUn, SysUtils, PersistenciaUn;

type
  // Test methods for class TFuncionario

  TestTFuncionario = class(TTestCase)
  strict private
    FFuncionario: TFuncionario;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestCalculoIR;
    procedure TestCalculoINSS;
  end;

implementation

procedure TestTFuncionario.SetUp;
begin
  FFuncionario := TFuncionario.Create(nil, TDGRSQLConnection.getInstance);
end;

procedure TestTFuncionario.TearDown;
begin
  FFuncionario.Free;
  FFuncionario := nil;
end;

procedure TestTFuncionario.TestCalculoINSS;
begin
  Self.FFuncionario.Salario := 1000;
  Self.FFuncionario.Dependentes.Edit;
  Self.FFuncionario.Dependentes.IDFuncionario := -1;
  Self.FFuncionario.Dependentes.Nome := 'Dependente Calculo INSS';
  Self.FFuncionario.Dependentes.IsCalculaINSS := True;
  Self.FFuncionario.Dependentes.Post;

  Check(Self.FFuncionario.INSS = 80, 'INSS inválido');
end;

procedure TestTFuncionario.TestCalculoIR;
begin
  Self.FFuncionario.Salario := 1000;
  Self.FFuncionario.Dependentes.Edit;
  Self.FFuncionario.Dependentes.IDFuncionario := -1;
  Self.FFuncionario.Dependentes.Nome := 'Dependente Calculo IR';
  Self.FFuncionario.Dependentes.IsCalculaIR := True;
  Self.FFuncionario.Dependentes.Post;

  Check(Self.FFuncionario.IR = 120, 'INSS inválido');
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTFuncionario.Suite);
end.

